### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by soodoku** [dcomtois/summarytools#10]
fyi, I get the following error:

```
Error in isTRUE(extra_space) : object 'extra_space' not found
```

Will try to post a reproducible example

**Comment by dcomtois** [comment]
Yes I got that too yesterday actually, not sure what causes it yet, but will check it out as soon as I can. Thanks for reporting it.

**Comment by soodoku** [comment]
I can trace it to int columns.

**Comment by soodoku** [comment]
expanding a bit more: 

1. there is a near 100% chance you know this but i wanted to share whatever little I know to be of help: extra_space is being called in dfSummary before it is being initialized when certain conditions are met. and that is the error. 

2. what i realized when i was going through dfSummary is that it is a super complicated function. I think it would be a good idea to split into multiple smaller functions as that can clarify the logic a bit more. My rec. for dplyr was also sort of based on that obs. We can write separate functions for handling each data type. that is how I went about it when i was writing my own summary function.

**Comment by dcomtois** [comment]
Fixed! Pls use devtools::install.github to reinstall the package. 

For re-writing, I agree it's a pretty huge function, but this is something that will need to wait as I'm super busy nowadays!
