### ISSUE TITLE
Stat column of dfsummary not formatted correctly

### ISSUE THREAD

**Issue by lbo34** [dcomtois/summarytools#106]
Hi,

I am trying to use dfsummary() inside a R notebook document (I am using OS X).
When I knit to HTML, I get the graphs... so I was excited, but the stat columns formatting is weird... see screenshot

![image](https://user-images.githubusercontent.com/18358046/74611346-ec845c00-50c8-11ea-93f1-4bd8c1a77594.png)

**Comment by dcomtois** [comment]
This is a css issue... To display line breaks in multi-line tables, we need to define `white-space: pre;`. Include it manually as inline html (using style tag), or see documentation on using `st_css()`.

**Comment by dcomtois** [comment]
Closing for now, if you still encounter problems let me know and will reopen.
