### ISSUE TITLE
stby function does not keep the order of name

### ISSUE THREAD

**Issue by Indigofera** [dcomtois/summarytools#107]
I have variables that are longitudinal  (day1, day4, day8, day11). When I used stby function to find descriptive statistics, the output looks like day1, day11, day4, day8. 

How can I keep the same order as (day1, day4, day8, day11). 

Thanks for helping.

**Comment by dcomtois** [comment]
Hello,

The easiest way would be to change the values day1, day2, day3... into day01, day02, day03...

**Comment by Indigofera** [comment]
Thanks!!
