### ISSUE TITLE
installation problem 

### ISSUE THREAD

**Issue by enderam** [dcomtois/summarytools#109]
Hi there, 

I installed the package as usual. Tried loading and even if it looks like it is installed there are a bunch of warnings and the functions do no work .

```
**install.packages("summarytools")**
Installing package into ‘/Users/me/Library/R/3.6/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/summarytools_0.9.6.tgz'
Content type 'application/x-gzip' length 889313 bytes (868 KB)
==================================================
downloaded 868 KB


The downloaded binary packages are in
	/var/folders/_4/gs19qnq14852pd4w150f6p9r0000gn/T//Rtmp0Pqila/downloaded_packages
**> library(summarytools)**
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: package or namespace load failed for ‘summarytools’:
 .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/tcltk/libs/tcltk.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/tcltk/libs/tcltk.so, 10): Library not loaded: /opt/X11/lib/libfontconfig.1.dylib
  Referenced from: /usr/local/lib/libtk8.6.dylib
  Reason: Incompatible library version: libtk8.6.dylib requires version 11.0.0 or later, but libfontconfig.1.dylib provides version 10.0.0
In addition: Warning message:
In system2("/usr/bin/otool", c("-L", shQuote(DSO)), stdout = TRUE) :
  running command ''/usr/bin/otool' -L '/Library/Frameworks/R.framework/Resources/library/tcltk/libs//tcltk.so'' had status 1
**> descr(exams)**
Error in descr(exams) : could not find function "descr"



```

**Comment by dcomtois** [comment]
Maybe try the solution mentionned here:

https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

**Comment by dstrants** [comment]
Same problem here. I tried:
* Installing from github
* resetting `xcode-select`
* reinstall r, studio and xquartz  through brew

But nothing really worked out.

**Comment by dcomtois** [comment]
Can you pls paste the error message(s) you get? Thx

**Comment by dstrants** [comment]
I thought it is very similar to the one above that's why I omitted it.

```
Warning: S3 methods ‘as.character.tclObj’, ‘as.character.tclVar’, ‘as.double.tclObj’, ‘as.integer.tclObj’, ‘as.logical.tclObj’, ‘as.raw.tclObj’, ‘print.tclObj’, ‘[[.tclArray’, ‘[[<-.tclArray’, ‘$.tclArray’, ‘$<-.tclArray’, ‘names.tclArray’, ‘names<-.tclArray’, ‘length.tclArray’, ‘length<-.tclArray’, ‘tclObj.tclVar’, ‘tclObj<-.tclVar’, ‘tclvalue.default’, ‘tclvalue.tclObj’, ‘tclvalue.tclVar’, ‘tclvalue<-.default’, ‘tclvalue<-.tclVar’, ‘close.tkProgressBar’ were declared in NAMESPACE but not found
Error: .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: Tcl/Tk support is not available on this system
Execution halted
ERROR: lazy loading failed for package ‘summarytools’
* removing ‘/usr/local/lib/R/3.6/site-library/summarytools’
```

**Comment by dcomtois** [comment]
I see... There seems to be other cases of this happening with other R packages... Unfortunately there's not much I can do other than recommend [Googling for this specific issue ](https://www.google.com/search?&ei=2CWbXuyzKY2KytMP5vi_qA0&q=%22error%3A+Tcl%2FTk+support+is+not+available+on+this+system%22&oq=%22error%3A+Tcl%2FTk+support+is+not+available+on+this+system%22&gs_lcp=CgZwc3ktYWIQAzIGCAAQFhAeMgYIABAWEB46BAgAEBM6CAgAEBYQHhATOggIABAHEB4QEzoGCAAQHhATULKKGlibkhpgh5YaaAFwAHgAgAG7AYgBzgOSAQMwLjOYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwjs__XxrfLoAhUNhXIEHWb8D9UQ4dUDCAs&uact=5 )and following the leads... 

I wish you luck (and patience), please let us know if you encounter a solution, as I'm sure this will happen to others as well.

Thx & take care

**Comment by dstrants** [comment]
Yes, you are right this is a more generic issue. I am still looking into it. I will definitely come back with the solution when I 'll find out. 

Thanks for the help and take care too!

**Comment by dcomtois** [comment]
Closing for now, but pls feel welcome to add any updates.
