### ISSUE TITLE
even when graph.col = FALSE, gives graph error

### ISSUE THREAD

**Issue by soodoku** [dcomtois/summarytools#11]
```
view(dfSummary(hehe, graph.col = FALSE), file = "data_summary.html", append = TRUE, footnote = NA)
Error in plot.window(xlim, ylim, "", ...) : need finite 'ylim' values
```

**Comment by dcomtois** [comment]
For sure it should not happen while graph.col is set to FALSE, so will need to fix that. Is there anything particular about some columns in hehe? (All NA's in one column for instance?) Thx!

**Comment by soodoku** [comment]
the dataframe hehe doesn't have any columns which only have NAs.

**Comment by dcomtois** [comment]
Could you pls try again after installing `dev-current` version?

`devtools::install_github('dcomtois/summarytools', ref='dev-current')`

**Comment by soodoku** [comment]
works!

**Comment by dcomtois** [comment]
Fix merged into master branch. Thank you!
