### ISSUE TITLE
"Stats/values" column's factor's are not listed above, when i use in Flexdashboard.

### ISSUE THREAD

**Issue by lhagwasuren** [dcomtois/summarytools#111]
Hi there, I faced problem with my dfSummary table in Flexdashboard. First pic is flexdashboard's issue, second pic is my viewer (inside Rstudio). Otherwise i want to get second pic's table in flexdashboard, Sorry about my bad english. I think you can undestand my issue from photos.

 
![image](https://user-images.githubusercontent.com/50734813/81641980-dcc0ad80-9454-11ea-81b5-3f9ed93e8d38.png)
![image](https://user-images.githubusercontent.com/50734813/81642049-0c6fb580-9455-11ea-8ccb-3dd2aa573572.png)

**Comment by lhagwasuren** [comment]
Any idea?

**Comment by dcomtois** [comment]
The linefeeds within cells can be be activated with the following bit of css:

```
.st-multiline {
  white-space: pre;
}

```
If you can insert this css bit somewhere in the process, either by using `st_css()` (see vignettes for more detailed instructions), or by another way specific to Flexdashboard (which I'm not familiar with), then the issue should be resolved.

Good luck and please let us know if you succeed! :)

**Comment by lhagwasuren** [comment]
Thanks to responsed my issue. Flexdashboard is just html document. But simple HMTL document's table give me this result (1st pic). I think there are problem with my code.
![image](https://user-images.githubusercontent.com/50734813/81667951-89f7ed80-9476-11ea-8992-7e17fa739ba2.png)
![image](https://user-images.githubusercontent.com/50734813/81667993-98460980-9476-11ea-949c-e8684b9b8fc2.png)

**Comment by lhagwasuren** [comment]
Sorry about my bad question. I find my solution from (github)[https://github.com/dcomtois/summarytools/issues/60#issuecomment-461245551]. 
My main mistake is omitting `result = 'asis'` and `st_css`
```{r, results='asis', echo=FALSE}
st_css()
```
