### ISSUE TITLE
dfSummary: NAs in the data seem to cause error

### ISSUE THREAD

**Issue by astraetech** [dcomtois/summarytools#113]
Hi,
In the larger datasets, NAs in the data seem to cause problems?The only difference between the ok data and the problem data is the size, 
```
> land_imp_pop_1_test %>% dfSummary() %>% view()
Error in lapply(strsplit(x_pad, ""), as.numeric) : 
  (converted from warning) NAs introduced by coercion
```
Here is the info on the data
```
> str(land_imp_pop_1_test )
tibble [1,280,986 x 341] (S3: tbl_df/tbl/data.frame)
```
dfSummary on the smaller subsets seem to work ok. There is no SF data in these which caused problems in my other ticket. Is there any way to debug this? Unfortunately, this is a grant proprietary data and can't share the full data where the error seems to happen.

**Comment by dcomtois** [comment]
Thx for reporting this... That bit of code is a bit problematic. It's already the main bottleneck in terms of processing time, and it seems it also causes issues with large dataframes. How large is your dataframe (in MB or GB)?

**Comment by maguiiiar** [comment]
I'm facing the same issue processing the dfSummary function to a dataframe of ~10GB.

**Comment by dcomtois** [comment]
@maguiiiar @astraetech could you confirm that this is still happening with the latest 'dev-current' branch installed using `devtools::` or `remotes::install_github()`?

**Comment by dcomtois** [comment]
Hi @astraetech and @maguiiiar ,

Did you have the same issue since the latest updates? If not I'll close this ticket. Thx.

**Comment by dcomtois** [comment]
Closing for now, if new info is provided I'll reopen.
