### ISSUE TITLE
#ctable: default behavior of `round.digits`

### ISSUE THREAD

**Issue by statzhero** [dcomtois/summarytools#114]
I was expecting the default for `ctable` to be 

`round.digits = st_options("round.digits")`

and not as the following

`round.digits = 1`, 

but perhaps that's more desired.

**Comment by dcomtois** [comment]
Hi, I had to work my memory here, but I think the decision was made out of concern for having tables too wide for a decimal that is in most cases not really needed. I think creating a separate ctable.round.digits global option would be preferable to the setting this value to 2. Is it worth it though? I'm curious to know other ppl's thoughts on this so pls feel free to weigh in!

**Comment by dcomtois** [comment]
Next version will have a ctable.round.digits global option
