### ISSUE TITLE
deprecation warning with dplyr, but output looked fine

### ISSUE THREAD

**Issue by shawnjanzen** [dcomtois/summarytools#115]
I ran my usual descr() function on a select number of columns
`descr(iv[,c(18:23)])`

and I received the output I expected to get, but it also came along with the following warning message:

```
Warning message:
`funs()` is deprecated as of dplyr 0.8.0.
Please use a list of either functions or lambdas: 

  # Simple named list: 
  list(mean = mean, median = median)

  # Auto named with `tibble::lst()`: 
  tibble::lst(mean, median)

  # Using lambdas
  list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated
```

Because of the 8 hour limit, I am not able to tinker and try to replicate the warning anytime soon; however, here is the output from the lifecycle::last_warnings() call.  It gave the same warning as above plus:
```
backtrace:
 1. summarytools::descr(iv[, c(18:23)])
 2. dplyr::funs(...)
```

Not sure if this is an actual issue or not.

**Comment by dcomtois** [comment]
Thanks for reporting this. I also saw it today actually... It shouldn't be too difficult to correct, will keep you posted.

**Comment by dcomtois** [comment]
Fixed. Install with `remotes::install_github` or `devtools::install_github` to get the latest version including this fix.
