### ISSUE TITLE
display problem in markdown

### ISSUE THREAD

**Issue by jt-neumann** [dcomtois/summarytools#116]
Thank you very much for providing this great package - dfSummary looks really perfect. Unfortunately I have a problem with correct display of the dfSummary output in the markdown html oder pdf file. Using "view(dfSummary" it looks perfect, but when knitting to PDF or html, the output is not rendered. I am running R 3.6.1 on a windows virtual machine.

The code is: 
<img width="597" alt="image" src="https://user-images.githubusercontent.com/51707544/85382541-6a2e0c00-b582-11ea-8f84-b27bc4adb882.png">

**Comment by dcomtois** [comment]
Hi,

You're very welcome :)

Did you follow guidelines from the Rmarkdown recommendations [vignette](https://cran.r-project.org/web/packages/summarytools/vignettes/Recommendations-rmarkdown.html)? In particular, setting knitr option results = 'asis' is essential (see toward the end of document). There are a few additional tips for pdf's in the vignette.

**Comment by dcomtois** [comment]
Closing for now. Let me know if problem persists. Thx.

PS: Try using "grid" instead of "multiline" if the only problem is with graphs.
