### ISSUE TITLE
descr doesn't keep column order

### ISSUE THREAD

**Issue by zx8754** [dcomtois/summarytools#117]
Can we keep column order same as input data (related to #21):

```R
library(dplyr)
library(summarytools)

colnames(mtcars[, 1:2])
# [1] "mpg" "cyl"
```
Below **both** give the same output:

```R
descr(mtcars[, 2:1], stats = c("mean", "sd", "min"), headings = FALSE)
descr(mtcars[, 1:2], stats = c("mean", "sd", "min"), headings = FALSE)
#                  cyl     mpg
# ------------- ------ -------
#          Mean   6.19   20.09
#       Std.Dev   1.79    6.03
#           Min   4.00   10.40
```

Related SO post:
 - [descr function is not keeping order of columns?](https://stackoverflow.com/q/62530124/680068)

**Comment by dcomtois** [comment]
Hi,

There is no way currently but it's on my todo list!

**Comment by dcomtois** [comment]
The dev-current branch now includes an "order" parameter for descr(). Values can be one of:

  - "sort"  
 - "preserve"  
 - vector of column names in the desired order

If you could test it and confirm it works, I'll then close the issue. Thx.

**Comment by zx8754** [comment]
@dcomtois tested on dev version, all good. Thank you.
