### ISSUE TITLE
NAs introduced by coercion error

### ISSUE THREAD

**Issue by kevin199011** [dcomtois/summarytools#121]
Hi, I was using dfSummary function on a data frame and below error was reported:
Error in lapply(strsplit(x_pad, ""), as.numeric) : 
  (converted from warning) NAs introduced by coercion

I checked the column which caused the issue and it's numeric type and no NA. I'm not sure why this is happening. Thank you!

Kevin

**Comment by dcomtois** [comment]
Hi Kevin,

I think this has been fixed in the dev-current branch. See main page for instructions on how to install it and let me know how it goes! Thx
