### ISSUE TITLE
Freezing while installing and/or loading summarytools

### ISSUE THREAD

**Issue by jcutler79** [dcomtois/summarytools#125]
Hi, I am new to using summarytools. I was able to install the CRAN version fine. But when I tried to load the library, rstudio just froze in the middle of the loading (there were a few lines of information printed to the console about loading, and then it just stopped). I tried doing the same on just R, and it froze as well. 

So next I tried installing the github version as instructed here, but this time the install itself just stopped midway through. It got through all the updates it does first, and then after printing these lines to the console it just got stuck for a very long time (like around 20 minutes):
* installing *source* package ‘summarytools’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
[ then it froze here for about 20 minutes ]

Is there something about my R or rstudio that might be the problem? I'm using rstudio 1.1.463 and R 3.6.1.

I can't remember having an issue like this for any other package I've installed and loaded.

If you need more info to troubleshoot please let me know.

**Comment by dcomtois** [comment]
Hi,

First time I hear about something like that too... What OS are you using? If other than Windows, have you installed the dependencies? 

You could also try installing earlier versions of the package from Github (using `ref='0-9-4'` for instance).

Cheers

**Comment by jcutler79** [comment]
I am using macOS Mojave 10.14.6. Though, I am not sure what the
dependencies in question are.

I will try the earlier package versions. Thanks!

**Comment by dcomtois** [comment]
Dependencies are listed on the main readme:

https://github.com/dcomtois/summarytools#required-mac-os

**Comment by jcutler79** [comment]
Oh, sorry for not paying closer attention. Thank you!

**Comment by jcutler79** [comment]
It totally worked!! Thanks a ton for reaching out so quickly!

**Comment by dcomtois** [comment]
You're welcome!
