### ISSUE TITLE
Graph alignment in `dfSummary`

### ISSUE THREAD

**Issue by statzhero** [dcomtois/summarytools#129]
I'm getting some weird alignments with the graph as shown below. I'm using the following command within a R markdown chunk (`results = "asis"`) document: 

```
summarytools::dfSummary(dta, 
     plain.ascii = FALSE, style = 'grid', graph.magnif = 0.75, valid.col = FALSE, tmp.img.dir = "/tmp")

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6
``` 

![Screen Shot 2020-10-08 at 09 20 21](https://user-images.githubusercontent.com/1837585/95464146-9ca02100-0947-11eb-9888-f5b62fc07930.png)

**Comment by dcomtois** [comment]
Is this the version from CRAN or from GitHub?

Try these:

- include st_css as detailed toward the end of the summarytools rmarkdown vignette
- load the package and call dfSummary, not summarytools::dfSummary
- Check if other css might conflict with summarytools' css

**Comment by dcomtois** [comment]
I realize now that what you're showing is a PDF rendered output. This is a known issue. If you find the solution pls share!
