### ISSUE TITLE
Retaining the order of varaibles

### ISSUE THREAD

**Issue by peckqyang** [dcomtois/summarytools#130]
Hi,

Thank you so much for developing such a great package!

I am trying to use your package to create a descriptive statistics table for academic purposes.

One issue I am running up into is that creating the descriptive table using desr() re-orders the original variables alphabetically. However, I would like it to retain the column ordering in the original table.

Am I missing some obvious way of retaining that order or is this functionality not available? If not, please consider adding it since it would be very helpful.

Thank you!

**Comment by dcomtois** [comment]
Thank you for your kind feedback.

Retaining order is possible is the upcoming version, which you can already install using either remotes:: or devtools::install_github("dcomtois/summarytools")

Best

**Comment by peckqyang** [comment]
Great thank you!
