### ISSUE TITLE
print.summarytools fails for integer vector 

### ISSUE THREAD

**Issue by skpmuc** [dcomtois/summarytools#134]
`print(freq(c(1L, 1L, 2L)))` fails as data_info$Data.type has length 0

**Comment by dcomtois** [comment]
Fixed now. Just reinstall using remotes or devtools:

`install_github("dcomtois/summarytools")`

Pls confirm that all works as expected. Thanks!

**Comment by skpmuc** [comment]
Works as expected now. Thanks for the fix!
