### ISSUE TITLE
dfSummary() fails if data frame has list columns

### ISSUE THREAD

**Issue by stefanocoretta** [dcomtois/summarytools#135]
R 4.0.3 (2020-10-10).
summarytools 0.9.8
tibble 3.0.6
macOS 11.2 (20D64)

`dfSummary()` fails if the tibble passed to it has list columns.

```r
library(summarytools)
library(tibble)
view(dfSummary(tibble(a = list(c(1, 2)))))
#> Error in withCallingHandlers(expr, warning = function(w) if (inherits(w,  : 
#>  'list' object cannot be coerced to type 'double'
```

**Comment by dcomtois** [comment]
Hi, could you provide a bit of context in which those list columns would occur, and what might be a sensible way to deal with that from the stand point of a dfSummary? Thx

**Comment by stefanocoretta** [comment]
Hello! There are multiple uses for list columns, for example to hold multidimensional data or non-tabular data, vectors of different lengths, data frames and so on. 

So there isn't really one general way to deal with list columns.

One simple solution could be to simply print out the type of list if the column is a list column (numeric, character, data frame, etc).

**Comment by dcomtois** [comment]
Fixed in upcoming version.
