### ISSUE TITLE
Met error when installing in Linux 

### ISSUE THREAD

**Issue by neowangkkk** [dcomtois/summarytools#137]
Hi, I cannot install it in the Linux environment. Here is the error message: 

Error: package or namespace load failed for ‘magick’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/wangtaow/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-magick/00new/magick/libs/magick.so':
  /home/wangtaow/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-magick/00new/magick/libs/magick.so: undefined symbol: _ZNK6Magick8GeometrycvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/wangtaow/R/x86_64-pc-linux-gnu-library/3.6/magick’
ERROR: dependency ‘magick’ is not available for package ‘summarytools’
* removing ‘/home/wangtaow/R/x86_64-pc-linux-gnu-library/3.6/summarytools’

**Comment by dcomtois** [comment]
Hi, did you install magick first, as explained there?

https://github.com/dcomtois/summarytools#required-mac-os

**Comment by dcomtois** [comment]
Closing as no further information was provided.
