### ISSUE TITLE
Can't load summarytools

### ISSUE THREAD

**Issue by g-arruda** [dcomtois/summarytools#138]
Hi, I've installed the package from github and Magick++

I'm facing this error:

"Error: package or namespace load failed for ‘summarytools’:
 .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: Can't find a usable init.tcl in the following directories: 
    /builddir/vendor/build/lib/tcl8.6 ./lib/tcl8.6 ./lib/tcl8.6 ./library ./library ./tcl8.6.9/library ./tcl8.6.9/library

This probably means that Tcl wasn't installed properly."

Pop!_OS 20.10
R microsoft 4.0.2
RStudio 1.4.1103

**Comment by dcomtois** [comment]
Hi... Try and search for ".onLoad failed in loadNamespace() for 'tcltk'", you'll see how other ppl dealt with this tcltk issue.

For instance:
https://stackoverflow.com/questions/25212800/error-onload-failed-in-loadnamespace-for-tcltk

**Comment by dcomtois** [comment]
Closing as there is not much I can do about this... if the problem persists, maybe StackOverflow or the R mailing list would be better suited for this particular problem.
