### ISSUE TITLE
suggest `results="asis"` in documentation

### ISSUE THREAD

**Issue by skolenik** [dcomtois/summarytools#140]
When the `Introduction.Rmd` vignette is talking about folding the `dfSummary()` into markdown, and shows `plain.ascii = FALSE, tmp.img.dir = "/tmp"` kinds of options, it is worth mentioning that the chunk that generates the output should go with `{r chunk_name, results="asis", warning=FALSE}` options (on my system, I am getting tons of warnings about not being able to connect to X11 display which I don't care at all about as long as the output is properly generated.)

This chunk option is mentioned in `Recommendations-rmarkdown.Rmd` file as a global option, which IMHO is a very brutal approach only applicable if all of one's markdown is a bunch of `dfSummary()` outputs.

Thank you for the very useful package!

**Comment by dcomtois** [comment]
Thanks for the feedback. I wasn't aware of those warnings, would you mind sharing a screen capture to show where / how they are displayed?

**Comment by dcomtois** [comment]
Added to upcoming version docs.
