### ISSUE TITLE
Appending in View

### ISSUE THREAD

**Issue by djmangen** [dcomtois/summarytools#143]
I can append freq() output in view if using the default RStudio working directory on a local hard drive.  When using a client-specific working directory changed using setwd() I can write original files but cannot append, getting the following error:

Error in print.summarytools(x, method = method, file = file, append = append,  : 
  'file' path is not valid - check that directory exists

**Comment by dcomtois** [comment]
Could you pls provide a reproducible example? I can't replicate the error based on only the information provided.

**Comment by dcomtois** [comment]
Closing as no additional info was provided. Will reopen if and when a reproducible example is given.
