### ISSUE TITLE
Problem in pasting tables 

### ISSUE THREAD

**Issue by NepalR** [dcomtois/summarytools#146]
Hello !!
I have been using summarytools pkg for tabulation of my data. Recently I upgraded my r and r studio into [R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"]
In earlier version of rstudio i could easily copy the tablulation generated from using ctable() and freq() function neat and clean like what it shows in console. Now I am getting some scattered values (not neat and clean) while pasting tables  in word document generated from using above function .

Is this something wrong with my r studio setup or is there something need to be fixed in package itself.

Thank you so much for developing this package.

Cheers

**Comment by dcomtois** [comment]
Hi, sorry for not responding earlier, I am super busy with work... Could you pls include some reproducible example as well as some screen captures of what you're describing? Having a before / after would be ideal, i.e. how it looked before the update versus how it looks now... I never copy/paste into Word so this would help me figure it out much faster. Thanks.

**Comment by NepalR** [comment]
> Hi, sorry for not responding earlier, I am super busy with work... Could you pls include some reproducible example as well as some screen captures of what you're describing? Having a before / after would be ideal, i.e. how it looked before the update versus how it looks now... I never copy/paste into Word so this would help me figure it out much faster. Thanks.

Hello,
Apologies for late response. Here are some reproducible examples followed by screen captures

### codes###
library(summarytools)
attach(starwars)
ctable(starwars$skin_color, starwars$sex)

Attached files
capture
![worderror](https://user-images.githubusercontent.com/85289210/123512681-8ccc9680-d6a8-11eb-8d5e-da85abe0fbe7.JPG)
s
![wordnoerror](https://user-images.githubusercontent.com/85289210/123512682-8e965a00-d6a8-11eb-9ab6-3d6a23727b38.JPG)
 (what it look on r console at present as well as in earlier version!!)
worderror (what it look while i paste output into word from r console)
wordnoerror(what it used to look like when i past output from r console to word document)

I am just a beginners of R. So there might be some technical lacking in running the code from my side.

Regards
Ram

![Capture2](https://user-images.githubusercontent.com/85289210/123512680-89d1a600-d6a8-11eb-8f31-b9f1c68015f3.JPG)

**Comment by NepalR** [comment]
![Capture2](https://user-images.githubusercontent.com/85289210/123512715-bd143500-d6a8-11eb-8c75-4f8e1077d1ae.JPG)
this is what it looks on r console at present and in earlier version of R

![worderror](https://user-images.githubusercontent.com/85289210/123512729-d87f4000-d6a8-11eb-92ab-437015a9c089.JPG)
this is what i get while i paste result from r console to word document

![wordnoerror](https://user-images.githubusercontent.com/85289210/123512748-ecc33d00-d6a8-11eb-9d4b-207dd7788238.JPG)
this is the one with no such issue which i used to get in word doucment while pasting from r console directly

Best Regards

**Comment by dcomtois** [comment]
Oh, would it just be that you must use a monospace font in Word, like Lucida Console or Courrier New? Or am I missing something?

**Comment by dcomtois** [comment]
Will reopen if follow-up is provided...
