### ISSUE TITLE
Q1 and Q3

### ISSUE THREAD

**Issue by spedygiorgio** [dcomtois/summarytools#15]
Hi, is it also possible to specify 25th and 75th percentiles (as Q1 and Q3) maybe? Cause they are frequently used as descriptive reporting. Best

**Comment by dcomtois** [comment]
Hi, good suggestion... Just to be sure, you're thinking of the `descr()` function, right?

**Comment by spedygiorgio** [comment]
Yes, the descr function!

**Comment by spedygiorgio** [comment]
Yes

Il gio 22 feb 2018, 05:21 Dominic Comtois <notifications@github.com> ha
scritto:

**Comment by dcomtois** [comment]
q1 and q3 have been added. Install with install_github to test it out! If any problems, I'll reopen the issue. Thx.
