### ISSUE TITLE
summarytools::freq and summarytools::ctable with integer data type

### ISSUE THREAD

**Issue by kellysaunders17** [dcomtois/summarytools#150]
Hey there - I'm looking to use the summarytools::freq and summarytools::ctable functions with integer data types but get the error message that variables need to be numeric. 

`summarytools::ctable(df$var1, df$var2)`

Both var1 and var2 are integers.

`Error in if (data_info$Data.type.x == trs("numeric")) { : argument is of length zero`

Could these functions work with integer data types? Thank you!

**Comment by dcomtois** [comment]
Hi, which version of summarytools do you use? If not the latest, please update to the latest and try again. Thx.

**Comment by kellysaunders17** [comment]
Oh great! I must not have been using the latest version. I'm now using the 1.0.0 version and all is working well. Thank you!
