### ISSUE TITLE
Error in nchar

### ISSUE THREAD

**Issue by PolStats** [dcomtois/summarytools#154]
Error in nchar(x) : invalid multibyte string, element 1 
when I run 
print(dfSummary(anes_timeseries_2016, graph.magnify=.75),)

Error in as.character(x) : 
  cannot coerce type 'closure' to vector of type 'character' 
when I run
print(dfSummary(anes_timeseries_2016, graph.magnify=.75), method=render)

**Comment by dcomtois** [comment]
Hi, sorry for not replying sooner... having very limited time, I'd really need a reproducible example pls. Thx.

**Comment by dcomtois** [comment]
Will reopen if a fully reproducible example is provided. From what I can see, there are syntactic problems in both examples; an extra comma in the first, and "render" should be quoted in the second.
