### ISSUE TITLE
Getting error using ctable()

### ISSUE THREAD

**Issue by Payamdel** [dcomtois/summarytools#156]
Hi,
When using ctable() in the package I encounter the following error:
`table error in sub(".+\\.(.*)0*", "\\1", temp row names) : object 'temp_rownames' not found
`
Any clues why?

**Comment by dcomtois** [comment]
Hi, sorry for not replying sooner... lots of catching up to do... Any reproducible example to show pls?

**Comment by dcomtois** [comment]
Probably fixed by latest merges... otherwise will reopen (but pls provide a reproducible example!)
