### ISSUE TITLE
descr crashes when only one summary statistics is specified

### ISSUE THREAD

**Issue by alexploner** [dcomtois/summarytools#159]
R 4.1.0 on Ubuntu 21.10, summarytools 1.0.0

Calls to descr that only specify one summary statistic will crash:

```r
> descr(rnorm(100), stats = "mean")
Error in if (colnames(output)[i] == "sd") { : argument is of length zero
```
Regardless whether I feed it a vector or a data frame:
```r
> descr(cars, stats = "mean")
Error in if (colnames(output)[i] == "sd") { : argument is of length zero
```
From a quick look with debug, the problem seems to be this line of code in descr:
```r
output <- output[, stats]
```
where the `output` object loses its data frame status; replacing it with 
```r
output <- output[, stats, drop = FALSE]
```
should solve the issue.

Thanks for a great package!

**Comment by dcomtois** [comment]
Thx for reporting this, should be fixed in next release.

**Comment by dcomtois** [comment]
Fixed.
