### ISSUE TITLE
dfSummary: options valid.col & na.col

### ISSUE THREAD

**Issue by athammad** [dcomtois/summarytools#16]
Dear Dominic, 

first of all, I want to say that your package is great! Thank you!!!

Second I have noticed that the two options  of `dfSummary` do not seem to work when set to false.
Am I doing something wrong?
here is an example with `iris`
`view(dfSummary(iris, varnumbers = FALSE, valid.col = FALSE, na.col = FALSE , omit.headings=TRUE))`

**Comment by dcomtois** [comment]
Thanks for your feedback and heads up, I'll look into it asap!

**Comment by dcomtois** [comment]
Fixed. Install using install_github until version 0.8.3 is released on CRAN. Thanks!

**Comment by athammad** [comment]
Thank you Dominic!!!
