### ISSUE TITLE
 library("summarytools") is giving error system might not have X11 capabilities; in case of errors when using dfSummary(), set st_options(use.x11 = FALSE) Warning message: no DISPLAY variable so Tk is not available 

### ISSUE THREAD

**Issue by Kmumuda** [dcomtois/summarytools#162]
system might not have X11 capabilities; in case of errors when using dfSummary(), set st_options(use.x11 = FALSE)
Warning message:
no DISPLAY variable so Tk is not available 
Its already installed as captured in the screen shot still unable to import it

![image](https://user-images.githubusercontent.com/98601791/164148326-00f6290a-e210-4252-9e8d-a91a2e1307f1.png)

**Comment by dcomtois** [comment]
Are you saying you can't load the package at all (with `library(summarytools)`) ?

**Comment by dcomtois** [comment]
Unclear whether the problem is... will reopen if more details are provided.
