### ISSUE TITLE
Absolute max for dfSummary? Error when max.distinct.values>220

### ISSUE THREAD

**Issue by SugarRayLua** [dcomtois/summarytools#197]
Hi, and thanks for making the great summary tools package!

I have a lot of unique text values in a dataset I'm working on and thus tried to set in dfSummary function:

max.distinct.values = 229 (I have 229 rows)

However, when I do so I get the following error in Microsoft R Open version 4.0 on Rgui Windows version:

Error: Rgui.exe: GeometryDoesNotContainImage 'C:pathToATempLocalFile.png' @ warning/attribute.c/GetImageBoundingBox/534

It doesn't give me that error when I set the max.distinct.values at 220

Is this a limitation of dfSummary or something else wrong with my package?

Thanks!

**Comment by dcomtois** [comment]
There is no limit in dfSummary's code. However, the `GeometryDoesNotContainImage`  is likely a limitation of ImageMagick,  which tries to write an incredibly "tall" image and runs into some brickwall. I was able to get to close to 2000 distinct values and got the same as you did. I would dig in that direction... [Try this search for instance](https://www.google.com/search?q=imagemagick+GeometryDoesNotContainImage)

**Comment by SugarRayLua** [comment]
Thank you!
