### ISSUE TITLE
Add n to summary statistics

### ISSUE THREAD

**Issue by NPS-ARCN-CAKN** [dcomtois/summarytools#198]
It would be nice to add the number of samples to the available summary statistics. These currently include “mean”, “sd”, “min”, “q1”, “med”, “q3”, “max”, “mad”, “iqr”, “cv”, “skewness”, “se.skewness”, “kurtosis”, “n.valid”, and “pct.valid”. I was always taught to provide the number of values being used to calculate mean, s.d., etc.

Great package BTW!

**Comment by dcomtois** [comment]
Good idea. Will try to push this in the next CRAN update

**Comment by dcomtois** [comment]
Just to make sure, you would like to have something called for instance "N.total" for the vector or for the current subgroup? (Another option would be to have N.missing. But displaying both is definitely an overkill)

**Comment by dcomtois** [comment]
Added to local dev branch, will be pushing shortly.
