### ISSUE TITLE
possible network complication with /tmp

### ISSUE THREAD

**Issue by SimpleAddress4390** [dcomtois/summarytools#199]
Hi.  I have developed a configuration that loops through dataframes, and produces those nice looking graphs in dfSummary.  All was good locally.  I am now working in a 'networked' environment and I get write errors with the same code.   I believe the issue is that it can't write to a local \tmp, but is trying to write to the root of the same drive as the code being executed?   I can't copy the code out, but have reproduced it manually here.  I've created a local c:\tmp folde on the network machine, as I have on the machines I do this kind of thing locally on, but running the network code ignores local disks (as far as I can tell) for writing to /tmp.

Code:

---
title: "SimpleV01"
author: "Friedman"
date: "2024-10-14"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

summarytools::st_options(
	bootstrap.css     = FALSE,       
	plain.ascii       = FALSE,       
	style             = "rmarkdown", 
	dfSummary.silent  = TRUE,        
	footnote          = NA,          
	descr.silent      = TRUE,        
	tmp.img.dir       = "/tmp",
	subtitle.emphasis = FALSE)       

library(summarytools)
library(tidyverse)

```

## R Markdown

```{r results='asis'}

dfList <- c("mtcars", "PlantGrowth")

for (df in dfList) {
	
	cat("\n### ", df, "\n")

	print(dfSummary(ungroup(get(df)), 
			headings     = FALSE,
         style        = 'grid',
         graph.magnif = 0.75,
         varnumbers   = TRUE,
         valid.col    = FALSE,
			method       = 'render'))
}
```

Render:
![image](https://github.com/user-attachments/assets/43cadded-b8e4-4c8c-b8f1-398272146ed4)

Successful (locally)
![image](https://github.com/user-attachments/assets/100fd1da-f03f-4fd6-b44c-f91ecdf00b84)

**Comment by SimpleAddress4390** [comment]
Read the manual, stupid.. .  

I changed it from /tmp to "." as per details, and it is writing in that location.  Not great, but still, better than an error.  I had a task scheduler job and would just clean up c:\tmp on every login.   I'll think of some other way to clean this..

**Comment by dcomtois** [comment]
Sorry I couldn't be of much help, let me know if you figure out more precisely what's going on

**Comment by SimpleAddress4390** [comment]
No worries.
Once I figured out that we could put

"C:/" 

Then we could automate cleanup using a scheduled task at log in. 

It is still kludgy and leaves files exposed, compared to knitr just controlling the location or dfSummary writing to an area knitr can cleanup, but I understand why that would be impossible to know from either side.

Regards
