### ISSUE TITLE
dfSummary: Freqs(% Valid) numerical vectors and integer proportions

### ISSUE THREAD

**Issue by wshropshire** [dcomtois/summarytools#20]
Hello, 

I have a .csv data file that I am reading into a data frame. When I run the dfSummary() function in the console or render on RMarkdown, although some integers are only two distinct values with 100% valid entries, the frequencies(%) are not printed on the output. Interestingly, some integers with <10 values will have printed out frequencies, but there really isn't any notable pattern to why these will print whereas the majority will not. When using an older version of summarytools (0.6.5), this frequency issue is not a problem. Is there something I can do besides go through all of my variables and convert them to factors to resolve this issue? Thanks and please let me know if I need to clarify anything. I'm relatively new to programming and R. :)

**Comment by dcomtois** [comment]
I see the issue. Thanks for pointing it out, I'll fix asap.

**Comment by dcomtois** [comment]
Fixed. To try it out, reinstall package using devtools :

`devtools::install_github("dcomtois/summarytools")`

**Comment by wshropshire** [comment]
Thanks appreciate it!

William C. Shropshire, MPH
PhD student, Epidemiology

Research Graduate Assistant
UTHealth Graduate School of Public Health | Epidemiology, Human Genetics and Environmental Sciences
Center for Antimicrobial Resistance and Microbial Genomics (CARMiG) at McGovern Medical School
6431 Fannin St. Houston, TX 77030 | MSE R.234 | (830)-708-2542

**Comment by kaisrec** [comment]
Tanks you
