### ISSUE TITLE
useNA in ctable

### ISSUE THREAD

**Issue by stjeandenise** [dcomtois/summarytools#22]
I am getting an error using ctable every time I try and set useNA to "no". It works just fine for "always" or "ifany".  Error is below:

Error in ctable(stjean$pnc5_new, stjean$preterm, prop = "t", useNA = "no") : 
  'useNA' must be one of 'ifany', 'always', or 'no'

**Comment by dcomtois** [comment]
Fixed, thanks for reporting this. Please install patched version using:

```
library(devtools)
install_github("dcomtois/summarytools")
```
