### ISSUE TITLE
Found issue with coefficient of variation (CV)

### ISSUE THREAD

**Issue by Payamdel** [dcomtois/summarytools#24]
Dear Dominic,
I found the package "summarytools" very useful! 

However, I also found that CV values are calculated inappropriately in the package. When viewing the relevant code contained in "descr.R", I found that CV values are calculated using
`ifelse("cv"   %in% stats, variable.mean / variable.sd, NA)`
As you know the correct formula to calculate coefficient of variation is: CV = (Standard Deviation (σ) / Mean (μ)), why this chunk needs to be replaced by 
`ifelse("cv"   %in% stats, variable.sd / variable.mean, NA)`

Best regards,
Payam

**Comment by dcomtois** [comment]
Yes indeed. Thanks for pointing it out. A new release is coming pretty soon, including this fix.
