### ISSUE TITLE
Name of variable (features) disappears when using descr() with by() in Shiny app

### ISSUE THREAD

**Issue by Payamdel** [dcomtois/summarytools#26]
The descr() function from R-package summarytools generates common central tendency statistics and measures of dispersion for numerical data in R.

When I use descr() with by() in a Shiny app, names of variable (features) contained in the data disappear and not displayed. Instead, the names are replaced by Var1, Var2, Var3 etc.

I do not really understand why the names disappear when I implement these code in the Shiny app (see below). 

# Install packages   
source("https://bioconductor.org/biocLite.R")
biocLite("ALL")
source("https://bioconductor.org/biocLite.R")
biocLite("Biobase")
install.packages('devtools')
library(devtools)
install_github('dcomtois/summarytools')

# Load packages
library("summarytools")
library(Biobase)
library("ALL") 

# Shiny Server
server <- function(input, output, session) {
output$summaryTable <- renderUI({
#-- Load the ALL data
data(ALL)  
#-- Subset
eset_object <- ALL [1:3,] # choose only 3 variables 
#-- The group of interest 
eset_groups <-"BT"
ALL_stats_by_BT <- by(data = as.data.frame(t(exprs(eset_object))), 
                        INDICES = (pData(eset_object)[,eset_groups]), 
                        FUN = descr, stats ="all", 
                        transpose = TRUE)

view(ALL_stats_by_BT,
        method = 'render',
        omit.headings = FALSE,
        bootstrap.css = FALSE)
})
}

# Shiny UI
ui <- fluidPage(theme = "dfSummary.css",
fluidRow(
uiOutput("summaryTable")
)
)

  **As a side note,  if one reads in the data as Global variable: eset_object <<- ALL [1:3,], the variable names will be displayed. But this is not a solution to the problem as it is wise to avoid global variables!**

**Comment by dcomtois** [comment]
See this [stackoverflow post ](https://stackoverflow.com/questions/51469095/name-of-variable-features-disappears-when-using-descr-with-by-in-shiny-app )for more...

**Comment by Payamdel** [comment]
I have now looked further into it and found that the problem occurs due to this line: rownames(output)[i] <- paste0("Var",i). I
f you replace this line with rownames(output)[i] <- paste0(colnames(x.df)[i]) the problem is solved! 

What do you think?

**Comment by dcomtois** [comment]
Actually no, this line is the "last resort" that applies only when previous attemps at recuperating rownames have failed.

**Comment by Payamdel** [comment]
Ok! 
But when I use: rownames(output)[i] <- paste0(colnames(x.df)[i]) in descr(), the names are visible!

**Comment by dcomtois** [comment]
Oh... Then I'll have a look at this as soon as I can... Glad you found a working solution... Pls let me know if you observe unwanted side-effects!

**Comment by Payamdel** [comment]
No side-effects observed! :)

**Comment by dcomtois** [comment]
It makes me realize I need to re-think the way attributes (in particular variable names) are retrieved. Things get complicated with `with()`, `by()`, and `lapply()` in general, but for the colnames part, I see that I can simplify things (and make them work with shiny, too). A big thanks for your input on this @Payamdel !

**Comment by Payamdel** [comment]
You are welcome! 
Hope there will be a new release/update for "summarytools" available on the net!

**Comment by Payamdel** [comment]
@dcomtois Could it be that the variable names are lost in Shiny due to the following codes in options.R ?

.st_env <- new.env(parent = emptyenv())
.st_env$tmpfiles <- c()

# Initialize list used by view() when printing an object of class "by"
.st_env$byInfo <- list()

**Comment by dcomtois** [comment]
Hi... I'm still abroad on vacation but I'll look into it as soon as I can. Thx

**Comment by dcomtois** [comment]
`descr` should work fine now in Shiny Apps... Could you pls test it on your side? The fix is in the devel branch, so you'll need to install it:

`devtools::install_github("dcomtois/summarytools", ref = "dev-current")`

As for your question regarding .st_env, this seems to work fine with Shiny. It's the environment where the information on iterative processes (when using `by` or `lapply`) are stored in order for `view` to output things neatly. Let me know if you observe problems in that area. Thx!

**Comment by Payamdel** [comment]
So nice to here from you!
I have tried to install the package using the code you provided here (i.e. devtools::install_github("dcomtois/summarytools", ref = "dev-current")). But unfortunately,  I get "Installation failed: Command failed (255)"
Any idea?

**Comment by dcomtois** [comment]
Hello!

Hmmm not sure why this happens. Can you install any other package with devtools::install_github? I saw that some people had problems with the unzipping, c.g.:

https://github.com/r-lib/devtools/issues/1722
https://github.com/r-lib/devtools/issues/638

**Comment by Payamdel** [comment]
The problem with installation is solved by setting `options(unzip = "internal")` before installing from github, as suggested by (https://github.com/r-lib/devtools/issues/1722). So thanks for that!
Gonna test descr function and let you know how it works on my Shiny app!

**Comment by Payamdel** [comment]
Congratulations! You solved the issue nicely!
I think the function works as a charm now :)
Hope there will be a new release/update of the package soon!
Cheers

**Comment by dcomtois** [comment]
Sure thing! Could you pls open a new issue for it and include a small
(simplest possible) reproducible case? Thanks!
>
>

**Comment by dcomtois** [comment]
Could you try again after reinstalling from devtools::install_github("dcomtois/summarytools") pls? I pushed the changes from the dev-current branch, I think it should work now.
