### ISSUE TITLE
Error from view(dfSummary(df))

### ISSUE THREAD

**Issue by KatherineKing** [dcomtois/summarytools#29]
I read a clean dataset in from SQL, and tried the below:
library(summarytools)
> view(dfSummary(df))
Error in plot.window(xlim, ylim, "", ...) : need finite 'ylim' values
In addition: Warning messages:
1: In n * h : NAs produced by integer overflow
2: In breaks[-1L] + breaks[-nB] : NAs produced by integer overflow
3: In n * h : NAs produced by integer overflow
4: In breaks[-1L] + breaks[-nB] : NAs produced by integer overflow

**Comment by dcomtois** [comment]
Can you please provide a bit more information about the data? For instance use `descr()`, or `dfSummary()` with `graph.col = FALSE`.

**Comment by dcomtois** [comment]
Closing for now, I'll reopen if problem still arises and more details are provided. Thx.
