### ISSUE TITLE
with() returns Var1 instead of the named variable

### ISSUE THREAD

**Issue by raheems** [dcomtois/summarytools#3]
data(exams)
with(exams, by(english, gender, descr))

returns descriptive statistics for "english" for each gender. However, the statistics table shows Var1 as the column name instead of showing the actual named variable (which would be english, in this case).

                    Var1
- - - - - - - - - - - - - -
             Mean  76.66
          Std.Dev   9.35
              Min   55.9
              Max   93.2
           Median   77.1
              mad   7.56
              IQR    8.2
               CV    8.2
         Skewness  -0.25
      SE.Skewness   0.58
         Kurtosis  -0.25

Was it intentional? If not, it would probably be a good idea to display the actual variable name

**Comment by dcomtois** [comment]
Yes this has been nagging me for a good while now. Var1 (or series of Var1-VarX when a dataframe is the argument) was a temporary workaround. I found that with `sys.status()$sys.calls` I can resolve this... when I get a chance!

**Comment by dcomtois** [comment]
New dev version now supports `with()` as well as `by()`. 

To install: 
`install_github("dcomtois/summarytools", ref="dev")`

Try a few examples... 
```
by(exams, INDICES = list(Gender=exams$gender), FUN = descr)
with(exams, descr(english))
with(tobacco, by(BMI, list(gender, smoker), descr))
```
