### ISSUE TITLE
Getting error "Error in ctable(... : Could not find function "ctable""

### ISSUE THREAD

**Issue by nickharrigan** [dcomtois/summarytools#31]
Getting error "Error in ctable... : Could not find function "ctable""

**Comment by dcomtois** [comment]
Can you please provide more information and if possible a reproducible example?

**Comment by nickharrigan** [comment]
It is one of my students. I'm going to try to log in to her computer tomorrow and solve. Will let you know what I find.

My guess is that for some reason her computer is not clearing an earlier version of summarytools that does not have ctable.

**Comment by dcomtois** [comment]
Closing, I'll reopen if problem still arises. Thx.
