### ISSUE TITLE
Controlling which stats to use in the case of numerical variables when using dfSummary()

### ISSUE THREAD

**Issue by Payamdel** [dcomtois/summarytools#33]
I'm wondering whether it is possible to control which Stats to be shown in the case of numerical variables when using dfSummary().
This is almost necessary to be able to control which Stats to use for numerical variables, particularity in the case of CV. This is because CV values should not be calculated for a data on a logarithmic scale!

**Comment by dcomtois** [comment]
Thx for the suggestion. I'm hesitant to add another parameter for this as there are already many, but maybe this could be automated (by checking distribution types).  I'll look into it.

**Comment by dcomtois** [comment]
I couldn't find reliable ways to identify the shape of distributions. So IQR/CV will have to stay until we find something. 

However IQR and CV and now removed when data is unary or binary. To try it out, install the 'dev-current' version from GitHub.

**Comment by Payamdel** [comment]
Good job! 👍 Thanks for the information!

**Comment by SDAMcIntyre** [comment]
How about allowing the user to choose the stats in the same way as in descr()?

**Comment by dcomtois** [comment]
@SDAMcIntyre It's feasible but to avoid weird layouts, and to make things manageable programmatically, I'm thinking of two options here (which are not mutually exclusive):

**Option 1.** Have predefined "sets of stats", where the current one would be the default and alternate sets could be created that fit / cohabit reasonably well in the cell.
**Option 2.** Allow custom stats that would each occupy a line in the cell. 

One thing is for sure: Unless some coders join in, this will have to wait, as I can barely keep up with the maintenance and the other features I'm working on. (I'm thinking maybe making a call for help on Twitter, if you have other ideas I'm all ears).

**Comment by dcomtois** [comment]
It's done! :)

Will be available on CRAN soon. Here's a document that explains how it works: https://htmlpreview.github.io/?https://github.com/dcomtois/summarytools/blob/master/doc/Custom-Statistics-in-dfSummary.html
