### ISSUE TITLE
feature: select columns in freq

### ISSUE THREAD

**Issue by ptoche** [dcomtois/summarytools#35]
New to the package. Very interesting contribution! I may have missed this: is there a way to select the columns that ``freq`` returns? I can remove NAs with ``report.nas = FALSE``.  I know I can drop the ``Totals`` row with ``totals = FALSE``. Is there an option of the ``freq`` function to keep/drop the percentage column and/or the cumulative percentage column? 

Something like ``report.cum = FALSE`` and ``report.pct = FALSE`` ...

**Comment by dcomtois** [comment]
I've added a parameter "cumul" to freq(). So now you can have 

```
> freq(tobacco$gender, cumul = FALSE, report.nas = FALSE, plain.ascii = FALSE)
Frequencies  
tobacco$gender  
Type: Factor  

           Freq       %
-------- ------ -------
       F    489   50.00
       M    489   50.00
```

Just install from the "dev-current" branch to try it out:

`devtools::install_github("dcomtois/summarytools", ref = "dev-current")`

**Comment by ptoche** [comment]
excellent!
