### ISSUE TITLE
strange result for character variable in dfSummary

### ISSUE THREAD

**Issue by vnijs** [dcomtois/summarytools#36]
I assume the percentage should always sum to 100% but in the screenshot below the "other" level gets 103.1% Not sure what is going on there. A link to the dataset used is provided below.

https://github.com/radiant-rstats/radiant.data/raw/master/data/titanic.rda

![image](https://user-images.githubusercontent.com/2998956/46574009-e2d5da80-c951-11e8-879b-f781977de24a.png)

**Comment by dcomtois** [comment]
Indeed something is not right... Will look into it ASAP. Thx

**Comment by dcomtois** [comment]
Fixed. Had to do with rounding of proportions being done too early (before summing). Will be issuing a new release on CRAN very soon.

**Comment by vnijs** [comment]
Thanks!
