### ISSUE TITLE
limiting the statistics in descr()

### ISSUE THREAD

**Issue by raheems** [dcomtois/summarytools#4]
This is a feature request. It would be great to add an argument to limit the statistics (mean, sd, etc.). For example, if someone only wants to return mean, median and sd , then the argument could be something like 

`stats = c('mean', 'median', 'sd') `

The final descriptive table would only return the above listed statistics instead of all of them. The default could be `stats = "all"`.

**Comment by dcomtois** [comment]
Good idea. On the #TODO list!

**Comment by dcomtois** [comment]
The new dev version includes that feature, among others... Still not thoroughly tested but several new features are also added (see NEWS).
