### ISSUE TITLE
Suggestion: how often does ID values exist

### ISSUE THREAD

**Issue by paulfeitsma** [dcomtois/summarytools#43]
When analyzing a data set with e.g. client ID's it is very usefull to know how often unique ID's appear in the dataset.  e.g. 90% appears once, 5% appears twice, etc.. (data frame summary)

**Comment by dcomtois** [comment]
Not sure how this is different from what is already in place, i.e. frequencies of most common strings / factors...?

**Comment by dcomtois** [comment]
After some thought, I find this very difficult to implement, as there is no way of knowing if a numeric column is in fact an ID... If users turn it into a factor however, then they'll get the frequencies.
