### ISSUE TITLE
Suggestion: mention it when an integer is a sequence

### ISSUE THREAD

**Issue by paulfeitsma** [dcomtois/summarytools#44]
When in the data frame summary an integer column contains for example 110 distinct values (0 < 43 < 109) it is useful to note that it is the sequence 0:109.

**Comment by dcomtois** [comment]
Not sure where that info would fit in... And with the graph, this aspect is made apparent (although not perfectly).

**Comment by paulfeitsma** [comment]
In the example below (PersonID variable) we could change "1000 distinct values" into "1000 distinct values (sequence 1:1000)". For integer sequences this would be the case when max(var) - min(var) + 1 = number of distinct values. I would suggest to only implement this enhancement for integer sequences.

![df_summary_example_salaries](https://user-images.githubusercontent.com/41962803/47991284-05424b80-e0ea-11e8-9da6-01e900c5e4bc.png)

**Comment by dcomtois** [comment]
I've added the "(Integer sequence)" note feature. Thanks for that good idea!
