### ISSUE TITLE
Suggestion: identify when an ID columns contains a checksum

### ISSUE THREAD

**Issue by paulfeitsma** [dcomtois/summarytools#45]
When a data set contains an ID which has a checksum, this is very useful to know. E.g. when bar codes are used (EAN https://en.wikipedia.org/wiki/International_Article_Number) it is very useful to know, especially when column names are not obvious.

**Comment by dcomtois** [comment]
Potentially feasible, but not sure where that information could be displayed... Also some implementation concerns -- false positives & slowing down the function in particular.

**Comment by dcomtois** [comment]
After reading about the different kinds of codes, I think it would be a good thing to add to dfSummary(). To avoid slowing down the function, we could check only a few dozens of values. There is some regex and math involved, nothing really difficult. Only tedious.

I put together useful links that describe validation rules. If you or anyone would like to contribute in translating them into R functions or chunks of code, it would raise the odds of having this feature in the next CRAN release. Let me know in a comment if you start working on any one of them, so we don't duplicate the work. I'll start with EAN and UPC.

**Wikipedia**
EAN: https://en.wikipedia.org/wiki/International_Article_Number
UPC: https://en.wikipedia.org/wiki/Universal_Product_Code

**Links with computational examples**
UPC/EAN: https://stackoverflow.com/questions/10143547/how-do-i-validate-a-upc-or-ean-code
UPC/EAN/ISBN/ISSN/JAN: http://www.azalea.com/upctools/
UPC/EAN/ISBN/ASIN: https://github.com/ThomasPe/ProductCodeValidator/tree/master/ProductCodeValidator

**Comment by dcomtois** [comment]
I was able to include the functionality for EAN and UPC codes. Feedback is welcome if anyone has time to try it out. I had a hard time finding example codes so I haven't done extensive testing.

**Comment by paulfeitsma** [comment]
I tested it using the file https://www.stedin.net/zakelijk/~/media/files/stedin/open-data/stedin_kleinverbruiksgegevens_01012018.zip in which the first column contains an EAN13. I used the following code to read the dataset and make a data frame summary.

````
library(data.table)
options(datatable.integer64="character")
dt_verbruik <- fread("20180129_OpenData_KV_Verbruiksdata_2018.csv")
view(dfSummary(dt_verbruik))
````

This gives the following error: "Error in paste0(counts_props, collapse = "\\\n") :  object 'counts_props' not found".

**Comment by dcomtois** [comment]
I think I know why... can you test with the latest version (dev-current) again? Otherwise, I'd be interested in having this dataset to run the checks on my side... Is it available somewhere online? Thx!

**Comment by dcomtois** [comment]
It's fixed. Works fine now. Thanks again!

**Comment by paulfeitsma** [comment]
I tested this feature by making a data frame summary of the file mentioned above with both the dev-current version (december 17th) and the CRAN version. You can see the results below.

![summarytools_checksum](https://user-images.githubusercontent.com/41962803/50240461-27a3d600-03c5-11e9-9e9f-18f9a857b9d1.png)

Below is the CRAN version and on top the dev-current version. The good news is that the EAN-13 network operator code was successfully being detected. Unfortunately in the stats/value column the min/max/mode summary is being displayed. In the Freqs column a long list of frequencies is being showed, which is not very readable/nice imho.

Therefore my suggestion would be to leave the stats/value and freqs column like the current CRAN version and mention in the variable column that an EAN-13 was being detected.

**Comment by dcomtois** [comment]
Makes sense!

**Comment by raheems** [comment]
Is the issue with showing histograms in rmarkdown resolved yet? I've just tried with the dev-current version and I do not notice any change. Thanks for the great work.

**Comment by dcomtois** [comment]
@raheems In the meantime, have you tried the settings described in the vignette [Recommendations for Using summarytools With Rmarkdown](https://cran.r-project.org/web/packages/summarytools/vignettes/Recommendations-rmarkdown.html)?

**Comment by raheems** [comment]
> @raheems In the meantime, have you tried the settings described in the vignette [Recommendations for Using summarytools With Rmarkdown](https://cran.r-project.org/web/packages/summarytools/vignettes/Recommendations-rmarkdown.html)?

Yes, thanks.

**Comment by dcomtois** [comment]
@paulfeitsma I made the changes necessary, haven't extensively tested it but so far looks better now.
@raheems  I've added the "col.widths" parameter to dfSummary(). See issue #57. Not sure if that is sufficient but I think it's a step in the right direction.

Thx
