### ISSUE TITLE
Suggestion: identify when there is a ID - Despription relation between two columns

### ISSUE THREAD

**Issue by paulfeitsma** [dcomtois/summarytools#46]
When using the data frame summary it is very handy when there are two columns that contain an ID and a description of something. For example when column 3 has distinct ID's 1 and 2 and column 123 contains the distinct values "MALE" and "FEMALE" it is very practical to mention that column 3 and column 123 are related.

**Comment by dcomtois** [comment]
I see what you mean. But where and how do you see that info displayed? There is here too a concern for false positives and impact on function speed.
