### ISSUE TITLE
Suggestion: mention most frequent value

### ISSUE THREAD

**Issue by paulfeitsma** [dcomtois/summarytools#47]
In the data frame summary if an column contains 115 distinct values (such as countries) and 99% of the values is a specific country, this is very useful to mention what the most frequent country is. In general I believe It is usefull to display to most frequent values.

**Comment by dcomtois** [comment]
Isn't it what it does already? The most frequent occurences are listed along with their frequencies. Am I misunderstanding your suggestion?

**Comment by paulfeitsma** [comment]
Let me try to this with an example (code below), with a sample data set with salaries. I found that many times there are always a few salaries that appear more often than others. In my example this are 1594.20 (minimum monthly wage in The Netherlands) and 2000. This will create the following data frame summary.

![df_summary_example_salaries](https://user-images.githubusercontent.com/41962803/47990258-60bf0a00-e0e7-11e8-9057-01930b3c26c5.png)

With regard to the 2nd column it would be handy if it would mention that values 1594.20 and 2000 appear most frequent. The first one you can see in the graph, but the value 2000 would be overlooked. 


`
minimum_wage <- 1594.20; 
df <- data.frame(PersonID = 1:1000 ,salary = c(sample(x = minimum_wage:5000, size = 600), rep(minimum_wage, 200), rep(2000,200))); 
view(dfSummary(df)); 
head(sort(table(df$salary), decreasing=TRUE));
`

**Comment by dcomtois** [comment]
Ah ok, I see now, thanks for clarifying... Deserves some thinking for sure!

**Comment by dcomtois** [comment]
After giving it some thought, I think this is a bit of an overkill. The mode will be shown for binary variables (issue #48) but otherwise, I think there's already a lot of info for numerical variables. I'll reopen if the feature is requested further in the future. Thx.
