### ISSUE TITLE
Suggestion: threat binary integers different

### ISSUE THREAD

**Issue by paulfeitsma** [dcomtois/summarytools#48]
In the data frame summary if an integer contains only 0 and 1's I believe it is not very useful to describe "mean (sd) : 0.23 (0.42) min < med < max : 0 < 0 < 1 IQR (CV) : 0 (1.82)". I suggest it is more usefull to mention how many 0 and 1 values occur.

**Comment by dcomtois** [comment]
Good point, the stats section for such variables should be simplified.

**Comment by dcomtois** [comment]
I've removed the IQR (CV) and replaced it with "mode : " (the frequencies already appear in following columns so no need to reprint them there). Will be in next release. Thx!
