### ISSUE TITLE
parameter to select which statistics to print

### ISSUE THREAD

**Issue by spedygiorgio** [dcomtois/summarytools#5]
Thanks for your great package. As a suggestion, I would like to propose to add a character vector parameter with default values to explicit which statistics are being tabulated to the descr function .

**Comment by dcomtois** [comment]
Thanks for your feedback! This feature is there in the future versions... You can already try it out this way:

```
install.packages("devtools")
library(devtools)
install_github('dcomtois/summarytools', ref='dev-noxtab')
```

**Comment by spedygiorgio** [comment]
Thanks for the prompt response, but in the list:
Which stats to produce. Either “all” (default), or a selection of : “min”, “median”, “max”, “mad”, “iqr”, “cv”, “skewness”, “se.skewness”, “kurtosis”, “N.Valid”, and “Pct.Valid”.
is missing the mean! Coud it be possibly added?

**Comment by dcomtois** [comment]
Oh that's actually an error in the documentation... you can also use "Mean" and "Std.Dev".

**Comment by spedygiorgio** [comment]
As a suggestion, I would rename std.dev as "sd" since it is the R standard conversion. However, very thanks for the update!

**Comment by dcomtois** [comment]
btw, "sd" is now the way to display standard-deviation (not std.dev), thanks for the good suggestion.
