### ISSUE TITLE
Suggestion: give information about date-time columns

### ISSUE THREAD

**Issue by paulfeitsma** [dcomtois/summarytools#50]
In the data frame summary when a column contains date/time information I would suggest to give a distribution of the days (e.g. monday 6%, tuesday 12%, etc..), months, hours, etc. This reveals easily season patterns, workday behavior, etc.

**Comment by dcomtois** [comment]
Hi Paul,
I'll close the issue but if you have more precise ideas about a function (sort of a variation of the `freq()` function for time objects), we can discuss it at some point. I'm pretty busy nowadays but I'll think about it on my side as well when I get a chance. Thx.
