### ISSUE TITLE
Calculation of percentage for "other" category seems incorrect

### ISSUE THREAD

**Issue by vnijs** [dcomtois/summarytools#51]
In a dataset with 75K unique identifiers (i.e., `id`). I see the output below. Shouldn't the percentage for "74990 other" be 100% or something very close to that?

![image](https://user-images.githubusercontent.com/2998956/47971622-25213300-e048-11e8-9d7c-e5cc8c2a851a.png)

**Comment by dcomtois** [comment]
Yes indeed. I'll investigate this ASAP.

**Comment by dcomtois** [comment]
Is this with version 0.8.8 of summarytools? I'm not able to reproduce the error... But I know something was off with 0.8.7.

**Comment by vnijs** [comment]
My apologies. Works fine in 0.8.8
