### ISSUE TITLE
Suggestion : add some <br> in the view(dfSummary(data),method = "render")

### ISSUE THREAD

**Issue by cecilesauder** [dcomtois/summarytools#55]
When I run 
`view(dfSummary(data))` in the console I get something like this 
<img width="582" alt="2018-12-14 11_03_08-data frame summary" src="https://user-images.githubusercontent.com/7116394/49996814-47d03100-ff90-11e8-992c-dbba2b3629c0.png">

but when I put 
`view(dfSummary(data), method = "render")` in my Rmd (html_output) , I get this : 

<img width="686" alt="2018-12-14 11_03_44-rapport sur dig reporting de decembre" src="https://user-images.githubusercontent.com/7116394/49996817-4acb2180-ff90-11e8-9fbf-8b0f8052aad1.png">

I think adding some `<br>` at the end each lines in `Stats / Values`  and `Freqs `  to have the same result that in the Rstudio Viewer could be very good :) 

Thanks for your package !

**Comment by dcomtois** [comment]
Bonjour Cécile,

Est-ce que le problème existe avec la version en développement seulement?

**Comment by dcomtois** [comment]
Hi Cecile, thanks for your feedback. This has to do with css... Check out the following vignette which gives working examples.

The line feeds are there (we can't put `<br>`'s inside a table cell per html specifications), there just needs to be a style element to tell the browser not to ignore them... Specifically, this is how summarytools does it: it includes this "chunk" in its css file (`summarytools.css`):

```
.st-multiline {
  white-space: pre;
}
```
... and the class "st-multiline" is given to dfSummary tables. If you look at the source html after for instance `print(dfSummary(iris), file = "~/test.html")`, you'll see it.

See the vignette and this link for another explanation: https://stackoverflow.com/questions/10937218/how-to-show-multiline-text-in-a-table-cell

... and let me know how this goes!

**Comment by cecilesauder** [comment]
Bonjour Dominic,
non ce problème est avec la version du CRAN, avec la version en
developpement je n'arrive pas à "render" mon fichier Rmarkdown. (Je vais
réssayer aujourd'hui avec tes nouveaux changements).

Le ven. 14 déc. 2018 à 19:22, Dominic Comtois <notifications@github.com> a
écrit :

> Bonjour Cécile,
>
> Est-ce que le problème existe avec la version en développement seulement?
>
>
>

**Comment by cecilesauder** [comment]
Hi Dominic, 
I solve the problem with what you specified in the vignette, I add the `summarytools.css` file in the yaml and now it's work ! 
Thanks for your help :) 
This problem was with the CRAN version of the package because with the dev-current version I couldn't `render` my . Rmd. 
I'm going to try again you new dev-current version today.
