### ISSUE TITLE
Error in ctable function:  $ operator is invalid for atomic vectors 

### ISSUE THREAD

**Issue by Ranlod** [dcomtois/summarytools#58]
When I use the `ctable` function with the pipe operator `%$%` from the package `magrittr` an error occurs:  **Error: $ operator is invalid for atomic vectors** 

``` R
library(summarytools)
library(magrittr)

tobacco %$% ctable(smoker, diseased)
```

Traceback
14. na.omit(c(parse_info_y$var_names, deparse(dnn[[2]]))) at ctable.R#194
13. ctable(smoker, diseased) 
12. eval(substitute(expr), data, enclos = parent.frame()) 
11. eval(substitute(expr), data, enclos = parent.frame()) 
10. with.default(., ctable(smoker, diseased)) 
9. with(., ctable(smoker, diseased)) 
8. function_list[[k]](value) 
7. withVisible(function_list[[k]](value)) 
6. freduce(value, `_function_list`) 
5. `_fseq`(`_lhs`) 
4. eval(quote(`_fseq`(`_lhs`)), env, env) 
3. eval(quote(`_fseq`(`_lhs`)), env, env) 
2. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
1. tobacco %$% ctable(smoker, diseased) 

Error appears in na.omit function in line 194, ctable.R file.
```R
y_name  <- na.omit(c(parse_info_y$var_names, deparse(dnn[[2]])))[1]
```

Many thanks.

**Comment by dcomtois** [comment]
I will look into that... In the meantime, is using `with()` a viable option for you?

**Comment by dcomtois** [comment]
Could you pls try again with the dev-current version and let me know if everything is okay? (Data frame name & label if present, variable names accurate in the headings section)

To install:
`devtools::install_github("dcomtois/summarytools", ref = "dev-current")`

Thx

**Comment by Ranlod** [comment]
When i used the command 
`devtools::install_github("dcomtois/summarytools", ref = "dev-current")`

The code `tobacco %$% ctable(smoker, diseased)` was successfully executed. Thanks!
