### ISSUE TITLE
handling NA in freq

### ISSUE THREAD

**Issue by spedygiorgio** [dcomtois/summarytools#6]
I see that freq always print NA and Cumulative Valid. I would suggest to add an boolean option, ignore.na=FALSE, that, when TRUE, ignores NA (and also does not print "Valid" frequencies columns

**Comment by dcomtois** [comment]
Thanks for your suggestion. A bit overworked these days but I will try to include this in the next official release.

**Comment by spedygiorgio** [comment]
Thanks

Il 01 nov 2017 08:22, "Dominic Comtois" <notifications@github.com> ha
scritto:

**Comment by dcomtois** [comment]
Sorry I haven't forgotten this, I just can't find time for it... if anyone can help, please let me know. Thanks

**Comment by dcomtois** [comment]
The option (argument) `report.nas` has (finally!) been added to `freq()` in the `dev-current` branch. To install and test out...
```
library(devtools)
install_github('dcomtois/summarytools', ref='dev-current')
```
Dominic

**Comment by spedygiorgio** [comment]
Thank you for the great news

Il sab 17 mar 2018, 05:09 Dominic Comtois <notifications@github.com> ha
scritto:
