### ISSUE TITLE
magic_image_write error when using dfSummary

### ISSUE THREAD

**Issue by ehsong** [dcomtois/summarytools#63]
Hi,

I wanted to produce a table in rmarkdown, so I followed the examples in introduction page and did the following with a data frame `df`:

```
dfSummary(df, plain.ascii = FALSE, style = "grid", 
          graph.magnif = 0.75, valid.col = FALSE, tmp.img.dir = "/tmp")
```

But I get an error message saying 

`Error in magick_image_write, RGB color space not permitted on grayscale PNG
`
Is there a way to get around this?

**Comment by dcomtois** [comment]
Hi Esther,

Could you pls provide the following info? 
- summarytools version 
- R Version
- Operating System 
- A small reproducible example of the problem

Meanwhile you can use the render method (using print); see vignettes for examples.

Thx

**Comment by dcomtois** [comment]
Also, if you could report the results you get when using 

`dfSummary(your_data, graph.col = F)` 

that you be very helpful. Thx

**Comment by dcomtois** [comment]
Closing until further information is provided, if issue is still unresolved.
