### ISSUE TITLE
Issue with weights in freq command

### ISSUE THREAD

**Issue by carlocharisma** [dcomtois/summarytools#71]
Hey,

I'm fairly new to R and loved your package for frequency tables.

It seems that there is an issue with the freq command when weights are used. The last value of a variable always gets coded as NA.
Here is an example from the console with a comparison from another package.

> summarytools::freq(onrm$bildung, weights = onrm$wei_onoz)
Weighted Frequencies  
onrm$bildung  
Type: Factor  
Weights: wei_onoz  

                 Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
----------- --------- --------- -------------- --------- --------------
          0   1064.96     50.88          50.88     32.74          32.74
          1   1028.28     49.12         100.00     31.61          64.35
       <NA>   1159.54                              35.65         100.00
      Total   3252.78    100.00         100.00    100.00         100.00

> wtd.table(onrm$bildung, weights= onrm$wei_onoz)
       0        1        2 
1064.961 1028.278 1159.538 

All observations for 2 gets a NA with the freq command. I tried this with several variables and got the same error.

I know this is a rough description, but I hope you can reproduce the error and fix it.
If you need any further output, just let me know.

Thanks.

**Comment by dcomtois** [comment]
Thanks for reporting this. I'll issue a fix ASAP.

**Comment by dcomtois** [comment]
Sorry for the delay, I have been on vacation but I'm back now, will issue a fix very soon.

**Comment by dcomtois** [comment]
Fixed. Please re-install using `devtools::install_github` (either the master branch or dev-current branch).
