### ISSUE TITLE
Percentile distribution for Numeric variables in dfSummary

### ISSUE THREAD

**Issue by shuvayan** [dcomtois/summarytools#74]
Hello,

I am not sure if the functionality is already there, but is there a way to get the percentile distribution too , for numeric variables in the output of dfSummary.
The Benford's law can be used I think for automatic datatype detection - not very sure about the accuracy of it though.
Kindly let me know your comments & the solution to percentile distributions.

**Comment by dcomtois** [comment]
Hi, for now there is no option for this in dfSummary. The `descr()` function does however give Q1, median and Q3. I'll look into the possibility of including it and at Benford's law over the following weeks. Thx!

**Comment by dcomtois** [comment]
See this document that explains how to add additional stats in dfSummary():
https://raw.githubusercontent.com/dcomtois/summarytools/master/doc/Custom-Statistics-in-dfSummary.pdf
