### ISSUE TITLE
the long characters was cut to 25 characters

### ISSUE THREAD

**Issue by jackpgao** [dcomtois/summarytools#76]
When using dfSummary, the result table shows the character only 25 characters length in 'Stats / Values' column.

Any parameters can set the max length to show, cause I can not see the true value of the data.

**Comment by dcomtois** [comment]
Yes there is: the `max.string.width` parameter takes care of that.

Cheers

**Comment by jackpgao** [comment]
Thanks~

BTW, it's very good data explorer tools.
