### ISSUE TITLE
Values in Columns not on separate lines

### ISSUE THREAD

**Issue by JamesMDorame** [dcomtois/summarytools#77]
When sending a dfSummary to view not all values in the Stats/Values column are on separate lines.  This is causing a mismatch between the Freqs column.  This is using all defaults.
Please see example.

![dfsummaryViewIssue](https://user-images.githubusercontent.com/23509941/61148735-10cde980-a4a5-11e9-8b2e-03ae1197eb99.PNG)

**Comment by dcomtois** [comment]
Hello and sorry for late reply... Would you mind trying installing the "dev-current" version from GitHub? Instructions can be found on this page: https://github.com/dcomtois/summarytools/tree/dev-current

Pls let me know if this helps... Thx!

**Comment by dcomtois** [comment]
Was this in the context of generating an Rmd document? If so, you'll need to look into `st_css()`

**Comment by dcomtois** [comment]
Closing until further information is provided... Thx
