### ISSUE TITLE
tb() function not working

### ISSUE THREAD

**Issue by jacopone** [dcomtois/summarytools#79]
Hi, 

I've tried to run the code provided in your documentation

grouped_descr <- stby(data = exams, INDICES = exams$gender, 
                      FUN = descr, stats = "common")
grouped_descr %>% tb()

The tb() call returns:
Error in if (attr(x, "st_type") == "freq") { : argument is of length zero

It seems that the tibble conversion is not working

My Sys.Info()

sysname                                             Linux
release                                 4.15.0-55-generic
version        #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019
nodename                                        linux-box
machine                                            x86_64

**Comment by dcomtois** [comment]
Hello,

What version of summarytools are you using? I suggest trying the "dev-current" branch on GitHub: https://github.com/dcomtois/summarytools/tree/dev-current

Pls let me know if this helps!

**Comment by dcomtois** [comment]
I wasn't able to reproduce problem... See if new version from CRAN (0.9.4) corrects the situation, if not let me know. Closing for now, thx.
