### ISSUE TITLE
Error loading summary tools

### ISSUE THREAD

**Issue by lanndoan** [dcomtois/summarytools#80]
I get the following error while loading in the package. Should I download an earlier version of R? OR is there a new equivalent of summary tools for later R versions?

`
> library(summarytools) # dfSummary
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: package or namespace load failed for ‘summarytools’:
 .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/tcltk/libs/tcltk.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/tcltk/libs/tcltk.so, 10): Library not loaded: /opt/X11/lib/libX11.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/tcltk/libs/tcltk.so
  Reason: image not found
In addition: Warning message:
In system2("/usr/bin/otool", c("-L", shQuote(DSO)), stdout = TRUE) :
  running command ''/usr/bin/otool' -L '/Library/Frameworks/R.framework/Resources/library/tcltk/libs//tcltk.so'' had status 1
`
My Sys.info( )
`Sys.info()
                                                                                           sysname 
                                                                                          "Darwin" 
                                                                                           release 
                                                                                          "18.6.0" 
                                                                                           version 
"Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64" 
                                                                                           machine 
                                                                                          "x86_64" 
                                                                           
> `

**Comment by dcomtois** [comment]
Hello, did you install the CRAN version or the GitHub version? If you installed it from CRAN, I'd suggest trying to install from GitHub, preferably the "dev-current" branch (https://github.com/dcomtois/summarytools/tree/dev-current), or the "master" branch. Pls let me know how it goes!

**Comment by lanndoan** [comment]
Downloading it from GitHub worked - thank you!

**Comment by dcomtois** [comment]
Great! Version 0.9.4 should be on CRAN any minute now, so things should be fine from here.
