### ISSUE TITLE
Using X11 and RStudio Server

### ISSUE THREAD

**Issue by DanielEWeeks** [dcomtois/summarytools#81]
Thank you for making the very nice and useful summarytools R package.  

I would like to get the graphics column of the 'dfSummary' command working from inside our RStudio Server which is running remotely on our cluster.

I have gotten ssh tunneling working so that RStudio Server is able to open an X11 window and so I have:
```
> isTRUE(capabilities("X11"))
[1] TRUE
```
However, when I run, using `summarytools_0.9.3`, 

```
> dfSummary(iris, plain.ascii = FALSE, style = "grid", 
+           graph.magnif = 0.75, valid.col = FALSE, tmp.img.dir = "/tmp")
```
the nice png graph column is not drawn, as this message is output:

```
'tmp.img.dir' will be ignored since system has no X11 capabilities
```

I'm not sure why this isn't working?

```
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE        TRUE        TRUE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE       FALSE        TRUE        TRUE        TRUE        TRUE 
```

I would appreciate any suggestions you might have.  Thank you.

**Comment by dcomtois** [comment]
This seems to happen on some systems, not sure why... One thing to try would be to update summarytools to 0.9.4, and if it still fails, try installing, if you can, this branch with devtools:

`devtools::install_github("dcomtois/summarytools", ref = "dev-no-x11-check")`

Let me know if this helps!

**Comment by KMBHPB** [comment]
Hi dcomtois, 

I have the identical issue, however I am just running it on my local machine (no RStudio Server).
A week ago the histograms were rendering without issue.

I will look forward to a solution.


Cheers,


Kai

**Comment by dcomtois** [comment]
@KMBHPB Have you tried the proposed temporary solution I mentionned?

**Comment by dcomtois** [comment]
The "dev-current" branch now incorporates changes that should help. Please let me know how it goes... Thx!

**Comment by miguelroboso** [comment]
I have the same issue. I have used `summarytools` in the past and everything seemed to run smoothly. 

I installed the `dev-current` branch, but I still get the ASCII output.

I take it that X11 capabilities are necessary?

**Comment by dcomtois** [comment]
There is now an option to specify if X11 should be used... if any problems still occur pls let me know and I'll reopen the issue. Thx.
