### ISSUE TITLE
Missing graph in dfSummary()

### ISSUE THREAD

**Issue by jakemkc** [dcomtois/summarytools#83]
Hi,

Last year I was using the summarytools package, and it works great.  At that time I did not need to install x11/xquartz to get dfsummary() to work correctly.

Today I tried to run summarytools again on other project, and after updating to the most recent version on CRAN, I was asked to install xquartz. After installing and rebooting the computer, I can run the following without errors:

`library(summarytools)`
`view(dfSummary(iris))`

However, I don't see the graph column in the output.

I would like to ask
1) why xquartz is not required to run previously
2) why the graph column is missing

Computer info:
system: MacOS 10.14.6
R: 3.5.1
summarytools: 0.9.4

Thanks!
Jake

**Comment by dcomtois** [comment]
Hello,

The reason for needing xquartz is, if I remember correctly, that it is necessary for Magick++ to work. And the reason why Magick++ is used is that some fine-tuning is done on the images (resizing/croping and the like).

As to why you don't see graphics, did you notice any message/warning in the console? I would suggest installing the dev-current version with devtools and see if it makes any difference:

`devtools::install_github("dcomtois/summarytools", ref = "dev-current")`

Thx!

**Comment by jakemkc** [comment]
Hello,

Thanks for the explanation.

I only have a warning message saying "package ‘summarytools’ was built under R version 3.5.2".

I uninstalled 0.9.4, restarted R, and installed 0.9.5 as suggested, and it solved my problem. Now I can see the graph column.

Thank you very much!

Jake

**Comment by dcomtois** [comment]
Great, thanks for your input!
