### ISSUE TITLE
XQuartz auto launch with Rstudio

### ISSUE THREAD

**Issue by jakemkc** [dcomtois/summarytools#87]
Hi,

Recently I have installed summarytools 0.9.5 to solve a display problem in dfSummary(). Right now whenever I launch Rstudio, XQuartz is also launched even I didn't load summarytools.

The auto launching of XQuartz does not happen when I run the native R.app, it's specific to Rstudio.

If I remove summarytools and restart Rstudio, no more auto launching of XQuartz with Rstudio.

Computer info:
system: MacOS 10.14.6
R: 3.5.1
Rstudio: 1.2.1335
summarytools: 0.9.5

Best,
Jake

**Comment by dcomtois** [comment]
This is becoming quite the puzzle... A few questions:

- Did this also happen with 0.9.4 ?
- I don't have an OS X machine right now, so I can't check... When you say XQuartz is launched, does it show an empty window, or does the application simply starts without any other effect?

I think we'll need to run this by the RStudio community...

**Comment by dcomtois** [comment]
From what I see after some google searches, it's a problem that has been going on with RStudio for some time now... Do you use packrat? See this link: 
https://github.com/rstudio/packrat/issues/308
