### ISSUE TITLE
Graph column not showing in shinyapps.io

### ISSUE THREAD

**Issue by deepanshu88** [dcomtois/summarytools#91]
When using dfSummary( ) function, graph column is appearing when I am running shiny app on local machine. When I am publishing the same app on shinyapps.io, graph column disappears.

```
print(dfSummary(getdataOriginal(),
                                     graph.magnif = 0.8,
                                     tmp.img.dir = "/tmp"), headings = FALSE, 
                           method = 'render', bootstrap.css = FALSE,
                           footnote ="Contact Us")

```

**Comment by dcomtois** [comment]
Most likely a write access issue in "/tmp". You can try "." or "./tmp" for instance.

**Comment by deepanshu88** [comment]
I tried both of them but none of them is working

**Comment by dcomtois** [comment]
I see... Not sure how shinyapps.io work, can you install a version of summarytools that is not on CRAN? If so, you could try installing the dev-current version, which resolves some X11-related problems.

**Comment by dcomtois** [comment]
Closing as no further info was provided, will reopen if I hear back from you. Thx.
