### ISSUE TITLE
dfSummary() fails if list columns are present

### ISSUE THREAD

**Issue by GegznaV** [dcomtois/summarytools#93]
If list columns are present, `dfSummary()` fails. 

```r
data(starwars, package = "dplyr")
dfSummary(starwars)
```
>Error in table(column_data, useNA = "no") : 
  all arguments must have the same length

Add support for list columns of at least ignore them with an appropriate warning.

```r
data(starwars, package = "dplyr")
sapply(starwars, class) %>% tibble::enframe()
```
```
 # A tibble: 13 x 2
   name       value    
   <chr>      <chr>    
 1 name       character
 2 height     integer  
 3 mass       numeric  
 4 hair_color character
 5 skin_color character
 6 eye_color  character
 7 birth_year numeric  
 8 gender     character
 9 homeworld  character
10 species    character
11 films      list     
12 vehicles   list     
13 starships  list
```   

PS.: I accidentally closed #92

**Comment by dcomtois** [comment]
Should be fixed now (at last!)... If anyone could test that would be nice :)

Just use remotes or devtools to install dev-current branch:

`remotes::install_github("dcomtois/summarytools", ref="dev-current")`
