### ISSUE TITLE
dfSummary() generates empty plot on Windows

### ISSUE THREAD

**Issue by GegznaV** [dcomtois/summarytools#94]
Either `dfSummary()` function or, most probably, its `print()` method generates an empty plot. The plot shouldn't be created at all.

![image](https://user-images.githubusercontent.com/12725868/66338485-e081d400-e949-11e9-8886-4830b9b7b78b.png)

If `graph.col = FALSE` is used, the plot is not generated. But the "plots" column is also missing.

This behavior (empty unnecessary plot) should be fixed.

**Comment by GegznaV** [comment]
Warning `NAs introduced by coercion` is also present. It should not be present.

**Comment by dcomtois** [comment]
For the empty plot, it will be fixed in upcoming version. For the NA's,
could you provide a reproducible example pls? Thx.

**Comment by GegznaV** [comment]
It seems that NA message appears only in R Markdown document.

    ``` {r setup}
    library(tidyverse)
    library(summarytools)
    ```

    ```{r}
    dfSummary(iris, graph.col = FALSE)
    ```

![image](https://user-images.githubusercontent.com/12725868/66347802-d23db300-e95d-11e9-90cb-b48a180790f3.png)

**Comment by dcomtois** [comment]
Can you pls retry after installing the `dev-current` version from github? 

`devtools::install_github("dcomtois/summarytools", ref = "dev-current")`

**Comment by GegznaV** [comment]
```r
devtools::install_github("dcomtois/summarytools", ref = "dev-current")
```
> Skipping install of 'summarytools' from a github remote, the SHA1 (01394c8d) has not changed since last install.
  Use `force = TRUE` to force installation

Both empty plot and NA issues still persist.

**Comment by dcomtois** [comment]
Sorry about the delay... Could you try and check the value of the following option pls?

`st_options('use.x11')`

**Comment by GegznaV** [comment]
`st_options('use.x11')` was `TRUE`. If I disable it, no empty plot is present:

![image](https://user-images.githubusercontent.com/12725868/67642130-55c14300-f911-11e9-825b-957618cc25de.png)

But I do not understand: isn't `x11` a graphical device for Unix-like OS'es, especially Linux? Shouldn't it be disabled on Windows by default?

**Comment by dcomtois** [comment]
See this page for details about x11 on Windows: https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/x11.html

As for the issue still persisting, I'm not sure what to make of it... I'd try forcing the reinstallation if possible.

**Comment by dcomtois** [comment]
Closing as this is likely resolved, if not just let me know and I'll reopen.

**Comment by gregkvas** [comment]
I've got the same issues described by GegznaV when using `summarytools` in R notebooks  (Windows 10 Pro Vers. 1803; RStudio Vers. 1.2.1335; R Vers. 3.5.3; summarytools Vers. 0.9.6)

After setting `st_options(use.x11 = FALSE)` the empty plot is NOT generated anymore, thx for that, but the output `NAs introduced by coercion` still remains (screenshot).

![image](https://user-images.githubusercontent.com/43455762/82820820-2d97c380-9ea3-11ea-9fd1-b53cdf956123.png)
