### ISSUE TITLE
[Feature Request] kableExtra integration or coloring functionality

### ISSUE THREAD

**Issue by RickPack** [dcomtois/summarytools#96]
Might tables produced by summarytools be modifiable by kableExtra? 

In particular, I am hoping to color cells by formula. kableExtra offers the _cell_spec_ function for that purpose per [this webpage](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html).

That webpage also indicates:

> Since the structure of kable is relatively simple, it shouldn’t be too difficult to convert HTML or LaTeX tables generated by other packages to a kable object and then use kableExtra to modify the outputs. If you are a package author, feel free to reach out to me and we can collaborate.

**Comment by dcomtois** [comment]
I'm not familiar with kableExtra, but I think it should work for `freq()` and `descr()` outputs after applying the `tb()` function.

`iris %>% descr() %>% tb() %>% kable() %>% kable_styling()`

For `ctable()` and `dfSummary()` outputs, I'm not sure about the feasibility though. I'll try and have a look at it when I get a chance.

**Comment by RickPack** [comment]
Success! Thank you, Dominic. I primarily wanted to do this in my `stby()` usage.
